channels:
  - conda-forge
dependencies:
  # run
  - galsim
  - fitsio
  - numpy
  - astropy
  - des-eastlake
  - galsim_extra
  - importlib_metadata
  - cfitsio  # for fpack
  - matplotlib-base
  # host setup.py
  - setuptools_scm
  - setuptools_scm_git_archive
