channels:
  - conda-forge
  - defaults
dependencies:
  # run
  - astropy
  - fitsio
  - galsim
  - galsim_extra
  - importlib_metadata
  - numpy
  # host setup.py
  - setuptools_scm
  - setuptools_scm_git_archive
  # host build for eastlake
  - autoconf
  - automake
  - blas-devel=*=*openblas
  - cfitsio
  - compilers
  - fftw
  - libtool
