channels:
  - conda-forge
  - defaults
dependencies:
  - autoconf
  - automake
  - blas-devel=*=*openblas
  - compilers
  - python=3.8
  - numpy
  - astropy
  - pyyaml
  - numba
  - scipy
  - cython
  - matplotlib
  - pybind11
  - fitsio
  - galsim
  - tqdm
  - h5py
  - cfitsio
  - ngmix=1.3
  - meds
  - metadetect
  - piff
  - esutil
  - des-desmeds
  - des-pizza-cutter
  - psfex
  - pixmappy
  - joblib
  - lsstdesc-coord
  - pip
  - galsim_extra
  - setuptools_scm
  - setuptools_scm_git_archive
  - importlib_metadata
