channels:
  - conda-forge
dependencies:
  # run
  - click
  - galsim
  - fitsio
  - numpy
  - astropy
  - hpgeom
  - scipy
  - esutil
  - pandas
  - des-eastlake
  - des-y6utils
  - galsim_extra
  - importlib_metadata
  - cfitsio  # for fpack
  # host setup.py
  - setuptools_scm
  - setuptools_scm_git_archive
