!!python/object/apply:collections.OrderedDict
- - - modules
    - - galsim.des
      - galsim_extra
      - montara
      - numpy
  - - pipeline
    - !!python/object/apply:collections.OrderedDict
      - - - steps
          - - galsim_montara
  - - delete_images
    - !!python/object/apply:collections.OrderedDict
      - - - delete_coadd
          - true
        - - delete_se
          - true
        - - save_tilenames
          - - DES0003-3832
  - - desy3cols
    - !!python/object/apply:collections.OrderedDict
      - - - shear_weight_grid
          - ${DESDATA}/y3_shape_w_grid_03_16_20_highsnr.txt
  - - delete_meds
    - !!python/object/apply:collections.OrderedDict
      - - - save_tilenames
          - - DES0003-3832
  - - all_tile_cats
    - !!python/object/apply:collections.OrderedDict
      - - - tag
          - null
  - - meds
    - !!python/object/apply:collections.OrderedDict
      - - - cutout_types
          - - image
            - weight
            - seg
            - bmask
        - - meds_dir
          - meds
        - - meds_run
          - y3v02
        - - sub_bkg
          - false
        - - add_psf_data
          - true
        - - use_joblib
          - true
  - - sof
    - !!python/object/apply:collections.OrderedDict
      - - - config_file
          - ${IMSIM_DIR}/ngmix_config/run-y3imsim-sof-psfinfile.yaml
        - - clobber
          - true
        - - use_joblib
          - true
  - - mcal
    - !!python/object/apply:collections.OrderedDict
      - - - config_file
          - ${IMSIM_DIR}/ngmix_config/run-y3imsim-mcal-nocorrect-psfinfile.yaml
        - - clobber
          - true
        - - use_joblib
          - true
  - - single_band_swarp
    - !!python/object/apply:collections.OrderedDict
      - - - config_file
          - ${IMSIM_DIR}/astromatic_config/Y3A1_v1_swarp.config
        - - swarp_cmd
          - swarp
        - - ref_mag_zp
          - 30.0
        - - update
          - !!python/object/apply:collections.OrderedDict
            - - - NTHREADS
                - 8
              - - PIXEL_SCALE
                - 0.263
              - - IMAGE_SIZE
                - 10000,10000
  - - swarp
    - !!python/object/apply:collections.OrderedDict
      - - - config_file
          - ${IMSIM_DIR}/astromatic_config/Y3A1_v1_swarp.config
        - - swarp_cmd
          - swarp
        - - center_from_header
          - true
        - - coadd_bands
          - - r
            - i
            - z
        - - mask_hdu
          - 1
        - - update
          - !!python/object/apply:collections.OrderedDict
            - - - RESAMPLE
                - N
              - - COPY_KEYWORDS
                - BUNIT,TILENAME,TILEID
              - - PIXEL_SCALE
                - 0.263
              - - IMAGE_SIZE
                - 10000,10000
              - - COMBINE_TYPE
                - CHI-MEAN
              - - NTHREADS
                - 32
              - - BLANK_BADPIXELS
                - Y
  - - sextractor
    - !!python/object/apply:collections.OrderedDict
      - - - sex_cmd
          - sex
        - - config_file
          - ${IMSIM_DIR}/astromatic_config/Y3A1_v1_sex.config
        - - params_file
          - ${IMSIM_DIR}/astromatic_config/deblend.param
        - - filter_file
          - ${IMSIM_DIR}/astromatic_config/Y3A1_v1_gauss_3.0_7x7.conv
        - - star_nnw_file
          - ${IMSIM_DIR}/astromatic_config/Y3A1_v1_sex.nnw
        - - update
          - !!python/object/apply:collections.OrderedDict
            - - - CHECKIMAGE_TYPE
                - SEGMENTATION,BACKGROUND,BACKGROUND_RMS
              - - DEBLEND_MINCONT
                - 0.001
              - - DETECT_THRESH
                - 1.1
              - - ANALYSIS_THRESH
                - 1.1
  - - eval_variables
    - !!python/object/apply:collections.OrderedDict
      - - - srun
          - e2e-test
        - - sstar_mag_col
          - &id002 !!python/object/apply:collections.OrderedDict
            - - - type
                - FormattedStr
              - - format
                - mag_%s
              - - items
                - - $band
        - - sgal_mag_col
          - &id001 !!python/object/apply:collections.OrderedDict
            - - - type
                - FormattedStr
              - - format
                - mag_%s_dered
              - - items
                - - $band
        - - ftruth_g
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - List
              - - items
                - - 0.0
                  - $float((@gal.items.0.ellip).g)
              - - index
                - '@current_obj_type_index'
        - - ftruth_beta
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - List
              - - items
                - - 0.0
                  - $float((@gal.items.0.ellip).beta.rad)
              - - index
                - '@current_obj_type_index'
        - - sz_col
          - photoz
  - - input
    - !!python/object/apply:collections.OrderedDict
      - - - catalog_sampler
          - !!python/object/apply:collections.OrderedDict
            - - - file_name
                - /global/project/projectdirs/des/y3-image-sims/input_cosmos_v4.fits
              - - cuts
                - !!python/object/apply:collections.OrderedDict
                  - - - mag_i
                      - - 15.0
                        - 25.0
                    - - isgal
                      - - 1
                    - - mask_flags
                      - - 0
                    - - bdf_hlr
                      - - 0.0
                        - 5.0
        - - desstar
          - !!python/object/apply:collections.OrderedDict
            - - - file_name
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - FormattedStr
                    - - format
                      - /global/cscratch1/sd/maccrann/DES/image_sims/star_cats_v0/stars-%s.fits
                    - - items
                      - - $tilename
              - - mag_i_max
                - 25.0
        - - des_piff
          - !!python/object/apply:collections.OrderedDict
            - - - file_name
                - $piff_path
  - - image
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - WideScattered
        - - border
          - 15
        - - random_seed
          - 1234
        - - nproc
          - 1
        - - nobjects
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - MixedNObjects
              - - ngalaxies
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - RandomPoisson
                    - - mean
                      - 170000
              - - use_all_stars
                - true
        - - xsize
          - 2048
        - - ysize
          - 4096
        - - world_pos
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - RADec
              - - ra
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - Degrees
                    - - theta
                      - !!python/object/apply:collections.OrderedDict
                        - - - type
                            - Random
                          - - min
                            - $ra_min_deg
                          - - max
                            - $ra_max_deg
              - - dec
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - Radians
                    - - theta
                      - !!python/object/apply:collections.OrderedDict
                        - - - type
                            - RandomDistribution
                          - - function
                            - math.cos(x)
                          - - x_min
                            - $numpy.radians(dec_min_deg)
                          - - x_max
                            - $numpy.radians(dec_max_deg)
  - - psf
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - DES_Piff
        - - use_substitute
          - $is_blacklisted
        - - no_smooth
          - false
        - - substitute_psf
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - Moffat
              - - beta
                - 3.0
              - - fwhm
                - 1.0
  - - gal
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - Sum
        - - items
          - - !!python/object/apply:collections.OrderedDict
              - - - type
                  - Exponential
                - - half_light_radius
                  - !!python/object/apply:collections.OrderedDict
                    - - - type
                        - catalog_sampler_value
                      - - col
                        - bdf_hlr
                - - ellip
                  - !!python/object/apply:collections.OrderedDict
                    - - - type
                        - GBeta
                      - - g
                        - !!python/object/apply:collections.OrderedDict
                          - - - type
                              - Eval
                            - - str
                              - np.sqrt(g1**2 + g2**2)
                            - - fg1
                              - !!python/object/apply:collections.OrderedDict
                                - - - type
                                    - catalog_sampler_value
                                  - - col
                                    - bdf_g1
                            - - fg2
                              - !!python/object/apply:collections.OrderedDict
                                - - - type
                                    - catalog_sampler_value
                                  - - col
                                    - bdf_g2
                      - - beta
                        - !!python/object/apply:collections.OrderedDict
                          - - - type
                              - Random
                - - flux
                  - !!python/object/apply:collections.OrderedDict
                    - - - type
                        - Eval
                      - - str
                        - 1-fracdev
                      - - ffracdev
                        - !!python/object/apply:collections.OrderedDict
                          - - - type
                              - catalog_sampler_value
                            - - col
                              - bdf_fracdev
            - !!python/object/apply:collections.OrderedDict
              - - - type
                  - DeVaucouleurs
                - - half_light_radius
                  - '@gal.items.0.half_light_radius'
                - - ellip
                  - '@gal.items.0.ellip'
                - - flux
                  - $1-@gal.items.0.flux
        - - flux
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - Eval
              - - str
                - 10**(0.4*(mag_zp-mag))
              - - fmag
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - catalog_sampler_value
                    - - col
                      - *id001
  - - star
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - Gaussian
        - - sigma
          - 1.0e-06
        - - flux
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - Eval
              - - str
                - 10**( 0.4 * (mag_zp - mag))
              - - fmag
                - !!python/object/apply:collections.OrderedDict
                  - - - type
                      - DESStarValue
                    - - col
                      - *id002
  - - stamp
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - MixedScene
        - - objects
          - !!python/object/apply:collections.OrderedDict
            - - - star
                - 0.2
              - - gal
                - 0.8
        - - obj_type
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - Eval
              - - str
                - object_type_list[i]
              - - ii
                - $obj_num-start_obj_num
        - - draw_method
          - auto
        - - shear
          - !!python/object/apply:collections.OrderedDict
            - - - type
                - G1G2
              - - g1
                - 0.02
              - - g2
                - 0.0
        - - gsparams
          - !!python/object/apply:collections.OrderedDict
            - - - maximum_fft_size
                - 16384
  - - output
    - !!python/object/apply:collections.OrderedDict
      - - - type
          - DESTile
        - - nproc
          - 32
        - - bands
          - - g
            - r
            - i
            - z
        - - desrun
          - y3v02
        - - desdata
          - /global/project/projectdirs/des/y3-image-sims
        - - noise_mode
          - from_weight
        - - add_bkg
          - false
        - - tilename
          - DES0003-3832
        - - blacklist_file
          - /global/homes/m/maccrann/DES/y3-wl_image_sims/input/piff_stuff/blacklist400.yaml
        - - badpixfromfits
          - !!python/object/apply:collections.OrderedDict
            - - - hdu
                - 1
              - - mask_hdu
                - 2
              - - mask_file
                - $orig_image_path
        - - weight
          - !!python/object/apply:collections.OrderedDict
            - - - hdu
                - 2
        - - truth
          - !!python/object/apply:collections.OrderedDict
            - - - columns
                - !!python/object/apply:collections.OrderedDict
                  - - - num
                      - obj_num
                    - - half_light_radius
                      - !!python/object/apply:collections.OrderedDict
                        - - - type
                            - Eval
                          - - str
                            - 0.0 if @current_obj_type=='star' else hlr
                          - - fhlr
                            - '@gal.items.0.half_light_radius'
                    - - g1
                      - $(@stamp.shear).g1
                    - - g2
                      - $(@stamp.shear).g2
                    - - g
                      - $truth_g
                    - - beta
                      - $truth_beta
                    - - obj_type
                      - '@current_obj_type'
                    - - obj_type_index
                      - '@current_obj_type_index'
                    - - band
                      - band
                    - - mag_zp
                      - $mag_zp
                    - - laigle_number
                      - !!python/object/apply:collections.OrderedDict
                        - - - type
                            - Eval
                          - - str
                            - -1 if @current_obj_type=='star' else int(laigle_number)
                          - - flaigle_number
                            - !!python/object/apply:collections.OrderedDict
                              - - - type
                                  - catalog_sampler_value
                                - - col
                                  - laigle_number
                    - - z
                      - !!python/object/apply:collections.OrderedDict
                        - - - type
                            - Eval
                          - - str
                            - -1. if @current_obj_type=='star' else z_gal
                          - - fz_gal
                            - !!python/object/apply:collections.OrderedDict
                              - - - type
                                  - catalog_sampler_value
                                - - col
                                  - $z_col
                    - - id
                      - $tile_start_obj_num + obj_num - start_obj_num
                    - - flux
                      - $float((@current_obj).flux)
                    - - mag
                      - $-2.5*np.log10((@current_obj).flux) + mag_zp
                    - - x
                      - $image_pos.x
                    - - y
                      - $image_pos.y
                    - - ra
                      - fra_val: $(@image.wcs).toWorld(@image_pos).ra / galsim.degrees
                        str: '''%.12e'' % (ra_val)'
                        type: Eval
                    - - dec
                      - fdec_val: $(@image.wcs).toWorld(@image_pos).dec / galsim.degrees
                        str: '''%.12e'' % (dec_val)'
                        type: Eval
                    - - gal_catalog_row
                      - fgal_catalog_row:
                          col: catalog_row
                          type: catalog_sampler_value
                        str: -1 if @current_obj_type=='star' else int(gal_catalog_row)
                        type: Eval
                    - - star_catalog_row
                      - fstar_catalog_row:
                          col: catalog_row
                          type: DESStarValue
                        str: -1 if @current_obj_type=='gal' else int(star_catalog_row)
                        type: Eval
        - - dir
          - /Users/beckermr/Desktop/des_y6_shear/montara/examples
